In [1]:
import numpy as np

In [14]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
p = 4

b = np.zeros((p, len(a)-2*p))

for i in range(p):
    b[i] = a[p+i:len(a)-p+i]


array([[ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]])

In [16]:
test = np.power(b,2).T

coef = [0.2, 0.5, 0.75, 0.25, 0.4]
sigma = np.zeros((len(test),1))

for i in range(len(sigma)):
    sigma[i] = coef[0] + coef

array([[ 25.,  36.,  49.,  64.],
       [ 36.,  49.,  64.,  81.],
       [ 49.,  64.,  81., 100.],
       [ 64.,  81., 100., 121.],
       [ 81., 100., 121., 144.],
       [100., 121., 144., 169.],
       [121., 144., 169., 196.],
       [144., 169., 196., 225.],
       [169., 196., 225., 256.],
       [196., 225., 256., 289.],
       [225., 256., 289., 324.],
       [256., 289., 324., 361.]])

In [35]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
p = 4

b = np.zeros((p, len(a)-2*p))

for i in range(p):
    b[i] = a[p+i:len(a)-p+i]
    
test = np.power(b,2).T
coef = [0.2, 0.5, 0.75, 0.25, 0.4]
const = np.ones((len(test),1))
summation = np.multiply(coef[1:], test)
const.shape, summation.shape
sigma = np.sum(np.concatenate((const, summation), axis=1), axis=1)

sigma

array([ 78.35, 104.15, 133.75, 167.15, 204.35, 245.35, 290.15, 338.75,
       391.15, 447.35, 507.35, 571.15])

In [31]:
np.sum(sigma, axis=1)

array([ 78.35, 104.15, 133.75, 167.15, 204.35, 245.35, 290.15, 338.75,
       391.15, 447.35, 507.35, 571.15])

In [36]:
h = np.ones((10,1))
h[:3] = 6
h

array([[6.],
       [6.],
       [6.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [37]:
max([2, 4])

4

In [1]:
c = list(range(10))
c

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
c[7:10]

[7, 8, 9]